config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => 'sidekiq'

  root 'batch/users#index'

  post 'batch/users', to: 'batch/users#create', as: :users_batch
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/file_handler.rb
class FileHandler < ApplicationRecord
  BYTE_SIZE_LIMIT = 1.gigabyte # just an example

  has_one_attached :csv

  def self.reached_byte_size_limit?
    blobs_byte_size = ActiveStorage::Blob.joins(:attachments)
                                         .where(active_storage_attachments: { record_type: name })
                                         .sum(:byte_size)
    blobs_byte_size > BYTE_SIZE_LIMIT
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :password, length: { in: 10..16 },
                       contains_lowercase: true, contains_uppercase: true,
                       contains_digit: true, no_repeating_character: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/batch/users_controller.rb
class Batch::UsersController < ApplicationController
  def index
    render inline: limit_message if reached_limit? # rubocop:disable Rails/RenderInline
  end

  def create
    redirect_to :index if reached_limit?
    @handler = FileHandler.new(file_handler_params)

    if @handler.save
      UserBatchUploadJob.perform_later(@handler)
      head :ok
    else
      render :index, status: :unprocessable_entity
    end
  end

  private

  def file_handler_params
    params.require(:file_handler).permit(:csv)
  end

  def limit_message
    <<~STR
      You have reached a limit of uploaded files.<br />
      Contact developer for renewal.<br />
      hhernanni@gmail.com
    STR
  end

  # temporary solution for limiting upload feature
  # so that we have a plan for bucket cost saving
  def reached_limit?
    FileHandler.reached_byte_size_limit?
  end
  helper_method :reached_limit?
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/batch/users/_default.html.erb
<li class='processing-message'>
  The result of processing your file will be shown here
</li>

app/views/batch/users/_invalid_response.html.erb
<li id="<%= "#{user.id}_response" %>" class='failure'>
  <span>(<%= user.id %>)</span>
  <span><%= user.name %> | </span>
  <span class='errors'><%= user.errors %></span>
</li>

app/views/batch/users/_valid_response.html.erb
<li class='success'>
  <span>(<%= user.id %>)</span>
  <span><%= user.name %></span>
</li>

app/views/batch/users/index.html.erb
<%= turbo_stream_from :users_batch %>
<header>
  <h1>Create users in batch</h1>
</header>

<main>
<%= form_with model: FileHandler.new, url: users_batch_path do |form| %>
  <div class='file-input-container'>
    <%= form.file_field :csv, direct_upload: !reached_limit? %>
    <%= link_to 'Sample', 'users-batch-sample.csv', class: 'sample' %>
  </div>

  <%= form.submit 'Submit', disabled: reached_limit? %>
<% end %>
</main>

<section>
  <h2>Users</h2>
  <ul>
    <%= turbo_frame_tag 'user_responses' do %>
      <%= render "default" %>
    <% end %>
  </ul>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BatchUserCreation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>